platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'Mantle', '~> 1.3'
pod 'SKBounceAnimation', '~> 1.0'
pod 'twitter-text-objc', '~> 1.6'
pod 'TTTAttributedLabel', '~> 1.7'
pod 'MAKVONotificationCenter', '~> 0.0.2'
pod 'SSKeychain', :git => 'https://github.com/soffes/sskeychain.git', :branch=>'master'
pod 'MTMigration', '~> 0.0.3'
